# Generated by Django 6.0.5 on 2026-05-21 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Остаток на складе')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='Способ доставки')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_app.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price_at_moment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент продажи')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm_app.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN-код')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Госномер')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём двигателя')),
                ('current_mileage', models.IntegerField(blank=True, null=True, verbose_name='Текущий пробег')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='crm_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='ServiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('oil_change', 'Замена масла'), ('filter_change', 'Замена фильтров'), ('brake_pads', 'Замена колодок'), ('seasonal_tires', 'Сезонная смена шин'), ('timing_belt', 'Замена ремня ГРМ'), ('coolant', 'Замена охлаждающей жидкости')], max_length=30, verbose_name='Тип напоминания')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего обслуживания')),
                ('last_service_mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег при последнем обслуживании')),
                ('interval_days', models.IntegerField(blank=True, null=True, verbose_name='Интервал в днях')),
                ('interval_km', models.IntegerField(blank=True, null=True, verbose_name='Интервал в км')),
                ('scheduled_date', models.DateField(verbose_name='Дата планируемой отправки')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('viewed', 'Просмотрено'), ('responded', 'Клиент откликнулся')], default='pending', max_length=20, verbose_name='Статус')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Согласие на получение')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес согласия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm_app.client', verbose_name='Клиент')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm_app.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Сервисное напоминание',
                'verbose_name_plural': 'Сервисные напоминания',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm_app.vehicle', verbose_name='Автомобиль'),
        ),
    ]
