# Generated by Django 6.0.5 on 2026-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_brands',
            field=models.TextField(blank=True, null=True, verbose_name='Совместимые марки (через запятую)'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_models',
            field=models.TextField(blank=True, null=True, verbose_name='Совместимые модели (через запятую)'),
        ),
    ]
