# Generated by Django 6.0.5 on 2026-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'Самовывоз (магазин)'), ('courier', 'Доставка курьером'), ('delivery', 'Доставка транспортной компанией')], max_length=20, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные при получении'), ('card', 'Банковская карта (онлайн)'), ('card_courier', 'Банковская карта курьеру'), ('bank_transfer', 'Безналичный расчет (для юрлиц)')], max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
