# Generated by Django 6.0.5 on 2026-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Завод-изготовитель'),
        ),
    ]
